"""initial schema

建 W5 增量（001 文档摄取管线）的全部 5 张表：users / knowledge_bases / documents /
chunks / processing_tasks。

- 本仓库此前没有任何表，故这是一次全新建表，不存在"给已有表加字段"。
- `knowledge_bases` / `documents.kb_id` / `uq_kb_user_name` / `idx_documents_kb` 的
  依据是 `docs/adr/0001-knowledge-base-entity.md`（2026-09-12 已批准）。
- 状态列落库为 VARCHAR（`native_enum=False`），避免 PG 原生枚举的 ALTER TYPE 负担。
- **本文件已生效即只增不改**（AGENTS.md §5）：后续结构变更一律新建修订。

Revision ID: 0001
Revises:
Create Date: 2026-09-12 11:04:35.557574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_bases_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases'))
    )
    op.create_index('uq_kb_user_name', 'knowledge_bases', ['user_id', 'name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'chunking', 'vectorizing', 'ready', 'failed', name='document_status', native_enum=False, length=20), server_default='uploaded', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_documents_kb_id_knowledge_bases')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('idx_documents_kb', 'documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_chunk_index')
    )
    op.create_table('processing_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Enum('uploaded', 'parsing', 'chunking', 'vectorizing', 'ready', 'failed', name='document_status', native_enum=False, length=20), server_default='uploaded', nullable=False),
    sa.Column('auto_retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('manual_retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_processing_tasks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_tasks')),
    sa.UniqueConstraint('document_id', name='uq_processing_tasks_document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_tasks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index('idx_documents_kb', table_name='documents')
    op.drop_table('documents')
    op.drop_index('uq_kb_user_name', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_table('users')
    # ### end Alembic commands ###
